import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { Amplify } from 'aws-amplify';
import outputs from '../amplify_outputs.json';
import App from './App.jsx';
import './index.css';

// Configure the Amplify client library with the deployed backend's settings.
// amplify_outputs.json is generated by `npx ampx sandbox` (or by a pipeline
// deploy). It is gitignored — each environment generates its own.
Amplify.configure(outputs);

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
